### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by stefanwerfling** [tarantir/egw-radio#1]
Where is the source code?

**Comment by tarantir** [comment]
The module does not work with EGW version > 16.x and is no longer maintained. I can share, but must be made to work with > 17.0. Let me know.

**Comment by stefanwerfling** [comment]
i would try, please share code. Use you EGW < 17.0 ?

**Comment by tarantir** [comment]
I was mistaken, EGW 14.x was the last release where I maintained this project. I would suggest get it running in 14.x and then try porting it to 17.x I am unable to provide support for this project as I do not have EGW 14.x. Good Luck!
